version: '1.0'

services:
  main:
    container_name: the-churras
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - API_URL=https://private-3c446b-thechurras.apiary-mock.com
    command: npm run dev
    ports:
      - 3000:3000