version: '1.0'

services:
  main:
    container_name: the-churras
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
    command: npm run dev
    ports:
      - 3000:3000